# Generated by Django 5.1 on 2025-02-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_delete_houseworker_delete_workerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.IntegerField(choices=[(1, 'Cleaning Services'), (2, 'Cooking Assistance'), (3, 'Babysitting'), (4, 'Gardening Services'), (5, 'Elder Care'), (6, 'Home Maintenance'), (7, 'Laundry Services'), (8, 'Custom Home Services'), (9, 'Others')])),
                ('contact', models.CharField(max_length=15)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
