# Generated by Django 5.1 on 2025-02-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_testprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprofile',
            name='service',
            field=models.IntegerField(choices=[(1, 'Consulting Services'), (2, 'Technical Support'), (3, 'Tutoring')]),
        ),
    ]
