# Generated by Django 5.1 on 2025-02-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_testprofile_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testprofile',
        ),
    ]
