# Generated by Django 5.1 on 2025-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_userdetails_delete_testprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AlterField(
            model_name='houseworkerprofile',
            name='service',
            field=models.CharField(choices=[('CLEANING', 'Cleaning'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('GARDENING', 'Gardening'), ('PAINTING', 'Painting')], max_length=100),
        ),
    ]
