# Generated by Django 5.1 on 2025-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_delete_userdetails_alter_houseworkerprofile_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseworkerprofile',
            name='service',
            field=models.CharField(choices=[('CLEANING SERVICES', 'Cleaning Services'), ('BABYSITTING', 'Babysitting'), ('COOKING ASSISTANCE', 'Cooking Assistance'), ('GARDENING SERVICES', 'Gardening Services'), ('ELDER CARE', 'Elder Care'), ('HOME MAINTENANCE', 'Home Maintenance'), ('LAUNDRY SERVICES', 'Laundry Services'), ('CUSTOM HOME SERVICES', 'Custom Home Services'), ('PLUMBING', 'Plumbing'), ('ELECTRICIAN', 'Electrician')], max_length=100),
        ),
    ]
