# Generated by Django 5.1 on 2025-02-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=15)),
                ('biography', models.TextField(blank=True, null=True)),
                ('selected_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.uniqueservicemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
